import { Router } from 'express';
import { z } from 'zod';
import * as controller from '../controllers/network.controller.js';
import { authenticate } from '../middlewares/auth.js';
import { validate } from '../middlewares/validate.js';
import * as schemas from '../schemas/network.schemas.js';

const objectId = z.string().regex(/^[a-f\d]{24}$/i);
const router = Router();
router.use(['/contacts', '/contact-requests', '/groups', '/group-invitations'], authenticate);
router.get('/contacts', validate({ query: z.object({ search: z.string().trim().max(100).optional() }) }), controller.contacts);
router.delete('/contacts/:id', validate({ params: schemas.idParams }), controller.removeContact);
router.patch('/contacts/:id', validate({ params: schemas.idParams, body: schemas.contactRelationBody }), controller.updateContact);
router.get('/contacts/:id/events', validate({ params: schemas.idParams, query: z.object({ from: z.string().datetime({ offset: true }), to: z.string().datetime({ offset: true }) }) }), controller.contactEvents);
router.get('/contact-requests', validate({ query: z.object({ direction: z.enum(['incoming', 'outgoing']).default('incoming') }) }), controller.requests);
router.post('/contact-requests', validate({ body: schemas.contactRequestBody }), controller.sendRequest);
router.put('/contact-requests/:id', validate({ params: schemas.idParams, body: schemas.contactResponseBody }), controller.respond);
router.get('/groups', controller.groups);
router.get('/group-invitations', controller.invitations);
router.put('/group-invitations/:id', validate({ params: schemas.idParams, body: schemas.invitationResponseBody }), controller.respondInvitation);
router.post('/groups', validate({ body: schemas.groupBody }), controller.createGroup);
router.post('/groups/join', validate({ body: schemas.joinGroupBody }), controller.joinGroup);
router.get('/groups/:id', validate({ params: schemas.idParams }), controller.group);
router.post('/groups/:id/members', validate({ params: schemas.idParams, body: schemas.groupMemberBody }), controller.addMember);
router.post('/groups/:id/invitations', validate({ params: schemas.idParams, body: schemas.groupInvitationBody }), controller.inviteMember);
router.post('/groups/:id/events', validate({ params: schemas.idParams, body: schemas.groupEventBody }), controller.groupEvent);
router.post('/groups/:id/transfer', validate({ params: schemas.idParams, body: schemas.transferOwnershipBody }), controller.transferGroup);
router.patch('/groups/:id/members/:memberId', validate({ params: z.object({ id: objectId, memberId: objectId }), body: schemas.updateMemberBody }), controller.updateMember);
router.delete('/groups/:id/members/:memberId', validate({ params: z.object({ id: objectId, memberId: objectId }) }), controller.removeMember);
router.post('/groups/:id/leave', validate({ params: schemas.idParams }), controller.leaveGroup);
router.delete('/groups/:id', validate({ params: schemas.idParams }), controller.deleteGroup);
export default router;
