import { recurrenceBetween } from './recurrence.js';

export const eventRangeQuery = (from, to) => ({ $or: [
  { recurrenceRrule: { $exists: true, $nin: [null, ''] }, $or: [
    { startsAt: { $lt: to } }, { 'recurrenceExceptions.overrides.startsAt': { $lt: to } }
  ] },
  { recurrenceRrule: { $in: [null, ''] }, startsAt: { $lt: to }, endsAt: { $gt: from } },
  { recurrenceRrule: { $exists: false }, startsAt: { $lt: to }, endsAt: { $gt: from } }
] });

// One expansion path for calendar rows, conflicts, sharing and reminders.
// A moved occurrence is addressed by its original slot, regardless of which
// date range contains its new start.
export const expandEvent = (event, from, to) => {
  const raw = event.toObject ? event.toObject() : event;
  if (!raw.recurrenceRrule) {
    return raw.startsAt < to && raw.endsAt > from
      ? [{ ...raw, occurrenceStartAt: raw.startsAt, occurrenceEndAt: raw.endsAt, occurrenceOriginalStartAt: raw.startsAt }]
      : [];
  }
  const duration = raw.endsAt.getTime() - raw.startsAt.getTime();
  const recurrence = { recurrenceRrule: raw.recurrenceRrule, startsAt: raw.startsAt, timeZone: raw.timeZone };
  const starts = new Map(recurrenceBetween({ ...recurrence, from: new Date(from.getTime() - duration), to })
    .map((start) => [start.getTime(), start]));
  const exceptions = new Map((raw.recurrenceExceptions || [])
    .map((exception) => [new Date(exception.originalStartAt).getTime(), exception]));
  for (const [key, exception] of exceptions) {
    if (exception.cancelled || !exception.overrides?.startsAt || starts.has(key)) continue;
    const movedStart = new Date(exception.overrides.startsAt);
    const movedEnd = exception.overrides.endsAt ? new Date(exception.overrides.endsAt) : new Date(movedStart.getTime() + duration);
    if (movedStart >= to || movedEnd <= from) continue;
    // A series edit may have invalidated an old exception. It must not
    // resurrect a date that is no longer generated by the current rule.
    const valid = recurrenceBetween({ ...recurrence, from: new Date(key - 1000), to: new Date(key + 1000) });
    if (valid.some((start) => start.getTime() === key)) starts.set(key, new Date(key));
  }
  return [...starts.values()].map((originalStartAt) => {
    const exception = exceptions.get(originalStartAt.getTime());
    if (exception?.cancelled) return null;
    const overrides = exception?.overrides || {};
    const occurrenceStartAt = overrides.startsAt ? new Date(overrides.startsAt) : originalStartAt;
    const occurrenceEndAt = overrides.endsAt ? new Date(overrides.endsAt) : new Date(occurrenceStartAt.getTime() + duration);
    if (occurrenceStartAt >= to || occurrenceEndAt <= from) return null;
    return {
      ...raw, ...overrides,
      // Overrides describe the row; the series anchor remains intact.
      startsAt: raw.startsAt, endsAt: raw.endsAt,
      occurrenceStartAt, occurrenceEndAt, occurrenceOriginalStartAt: originalStartAt
    };
  }).filter(Boolean).sort((a, b) => a.occurrenceStartAt - b.occurrenceStartAt);
};
